services:
    coloc_matching.core.entity_dao:
        class: ColocMatching\CoreBundle\DAO\EntityDao
        abstract: true
        arguments: ["@doctrine.orm.entity_manager"]
        lazy: true


    coloc_matching.core.user_dao:
        class: ColocMatching\CoreBundle\DAO\UserDao
        parent: coloc_matching.core.entity_dao
        lazy: true


    coloc_matching.core.announcement_dao:
        class: ColocMatching\CoreBundle\DAO\AnnouncementDao
        parent: coloc_matching.core.entity_dao
        lazy: true


    coloc_matching.core.historic_announcement_dao:
        class: ColocMatching\CoreBundle\DAO\HistoricAnnouncementDao
        parent: coloc_matching.core.entity_dao
        lazy: true


    coloc_matching.core.group_dao:
        class: ColocMatching\CoreBundle\DAO\GroupDao
        parent: coloc_matching.core.entity_dao
        lazy: true


    coloc_matching.core.visit_dao:
        class: ColocMatching\CoreBundle\DAO\VisitDao
        parent: coloc_matching.core.entity_dao
        lazy: true


    coloc_matching.core.user_token_dao:
        class: ColocMatching\CoreBundle\DAO\UserTokenDao
        parent: coloc_matching.core.entity_dao
        lazy: true


    coloc_matching.core.group_conversation_dao:
        class: ColocMatching\CoreBundle\DAO\GroupConversationDao
        parent: coloc_matching.core.entity_dao
        lazy: true


    coloc_matching.core.group_message_dao:
        class: ColocMatching\CoreBundle\DAO\GroupMessageDao
        parent: coloc_matching.core.entity_dao
        lazy: true
