services:
    coloc_matching.core.user_dto_manager:
        class: ColocMatching\CoreBundle\Manager\User\UserDtoManager
        arguments:
            - "@logger"
            - "@doctrine.orm.entity_manager"
            - "@coloc_matching.core.user_dto_mapper"
            - "@coloc_matching.core.form_validator"
            - "@security.password_encoder"
            - "@coloc_matching.core.profile_picture_dto_mapper"
            - "@coloc_matching.core.profile_dto_mapper"
            - "@coloc_matching.core.announcement_preference_dto_mapper"
            - "@coloc_matching.core.user_preference_dto_mapper"
            - "@event_dispatcher"
        lazy: true


    coloc_matching.core.announcement_dto_manager:
        class: ColocMatching\CoreBundle\Manager\Announcement\AnnouncementDtoManager
        arguments:
            - "@logger"
            - "@doctrine.orm.entity_manager"
            - "@coloc_matching.core.announcement_dto_mapper"
            - "@coloc_matching.core.form_validator"
            - "@coloc_matching.core.user_dto_mapper"
            - "@coloc_matching.core.housing_dto_mapper"
            - "@coloc_matching.core.comment_dto_mapper"
            - "@coloc_matching.core.announcement_picture_dto_mapper"
        lazy: true


    coloc_matching.core.historic_announcement_dto_manager:
        class: ColocMatching\CoreBundle\Manager\Announcement\HistoricAnnouncementDtoManager
        arguments:
            - "@logger"
            - "@doctrine.orm.entity_manager"
            - "@coloc_matching.core.historic_announcement_dto_mapper"
            - "@coloc_matching.core.comment_dto_mapper"
        lazy: true


    coloc_matching.core.group_dto_manager:
        class: ColocMatching\CoreBundle\Manager\Group\GroupDtoManager
        arguments:
            - "@logger"
            - "@doctrine.orm.entity_manager"
            - "@coloc_matching.core.group_dto_mapper"
            - "@coloc_matching.core.form_validator"
            - "@coloc_matching.core.user_dto_mapper"
            - "@coloc_matching.core.group_picture_dto_mapper"
        lazy: true


    coloc_matching.core.visit_dto_manager:
        class: ColocMatching\CoreBundle\Manager\Visit\VisitDtoManager
        arguments:
            - "@logger"
            - "@doctrine.orm.entity_manager"
            - "@coloc_matching.core.visit_dto_mapper"
            - "@coloc_matching.core.user_dto_mapper"
        lazy: true


    coloc_matching.core.invitation_dto_manager:
        class: ColocMatching\CoreBundle\Manager\Invitation\InvitationDtoManager
        arguments:
            - "@logger"
            - "@doctrine.orm.entity_manager"
            - "@coloc_matching.core.invitation_dto_mapper"
            - "@coloc_matching.core.form_validator"
            - "@coloc_matching.core.user_dto_mapper"
        lazy: true


    coloc_matching.core.private_conversation_dto_manager:
        class: ColocMatching\CoreBundle\Manager\Message\PrivateConversationDtoManager
        arguments:
            - "@logger"
            - "@doctrine.orm.entity_manager"
            - "@coloc_matching.core.private_conversation_dto_mapper"
            - "@coloc_matching.core.private_message_dto_mapper"
            - "@coloc_matching.core.form_validator"
            - "@coloc_matching.core.user_dto_mapper"
        lazy: true


    coloc_matching.core.user_token_dto_manager:
        class: ColocMatching\CoreBundle\Manager\User\UserTokenDtoManager
        arguments:
            - "@logger"
            - "@coloc_matching.core.user_token_dao"
            - "@coloc_matching.core.user_token_dto_mapper"
        lazy: true


    coloc_matching.core.group_conversation_dto_manager:
        class: ColocMatching\CoreBundle\Manager\Message\GroupConversationDtoManager
        arguments:
            - "@logger"
            - "@coloc_matching.core.form_validator"
            - "@coloc_matching.core.group_conversation_dao"
            - "@coloc_matching.core.group_dao"
            - "@coloc_matching.core.user_dao"
            - "@coloc_matching.core.group_conversation_dto_mapper"
            - "@coloc_matching.core.group_message_dto_mapper"
