# Routing pour la racine des Web services
coloc_matching.core.api:
    type: annotation
    resource: ColocMatching\CoreBundle\Controller\Rest\v1\RootController

# Routing pour les Web services /auth-tokens
coloc_matching.core.api.authentication:
    type: annotation
    resource: ColocMatching\CoreBundle\Controller\Rest\v1\AuthenticationController

# Routing pour les Web services /users
coloc_matching.core.api.user:
    type: annotation
    resource: ColocMatching\CoreBundle\Controller\Rest\v1\UserController

# Routing pour les Web services /announcements/visits et /announcements/{id}/visits
coloc_matching.core.api.announcement_visit:
    type: annotation
    resource: ColocMatching\CoreBundle\Controller\Rest\v1\Visit\AnnouncementVisitController

# Routing pour les Web services /announcements
coloc_matching.core.api.announcement:
    type: annotation
    resource: ColocMatching\CoreBundle\Controller\Rest\v1\AnnouncementController

# Routing pour les Web services /history/announcements
coloc_matching.core.api.historic_announcement:
    type: annotation
    resource: ColocMatching\CoreBundle\Controller\Rest\v1\HistoricAnnouncementController
    
# Routing pour les Web services /groups
coloc_matching.core.api.group:
    type: annotation
    resource: ColocMatching\CoreBundle\Controller\Rest\v1\GroupController