# Routing vers l'API REST d'Appartoo
coloc_matching.api.v1:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix: /rest
    options:
        expose: true
        
# Routing pour /hello
hello:
    resource: "@CoreBundle/Controller/HelloController.php"
    type: annotation
    prefix: /hello