# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
imports:
    - { resource: "@CoreBundle/Resources/config/services.yml" }
    - { resource: "@MailBundle/Resources/config/services.yml" }
    - { resource: "@RestBundle/Resources/config/services.yml" }

parameters:
#    parameter_name: value

services:
    coloc_matching.doctrine_cache.apcu:
        class: Doctrine\Common\Cache\ApcuCache

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }