# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
imports:
    - { resource: "@CoreBundle/Resources/config/services.yml" }

parameters:
#    parameter_name: value

services:
    coloc_matching.cache.adapter:
        class: "Doctrine\\Common\\Cache\\ApcuCache"