jms_serializer:
    visitors:
        json_serialization:
            # json_encode options bitmask, suggested JSON_PRETTY_PRINT in development
            options:
                - JSON_PRETTY_PRINT
                - JSON_UNESCAPED_SLASHES
                - JSON_PRESERVE_ZERO_FRACTION
        json_deserialization:
            # json_encode options bitmask, suggested JSON_PRETTY_PRINT in development
            options:
                - JSON_PRETTY_PRINT
                - JSON_UNESCAPED_SLASHES
                - JSON_PRESERVE_ZERO_FRACTION

