services:
    coloc_matching.rest.authentication_controller:
        class: ColocMatching\RestBundle\Controller\Rest\v1\AuthenticationController
        arguments:
            - "@logger"
            - "@jms_serializer"
            - "@coloc_matching.core.user_dto_manager"
            - "@coloc_matching.core.jwt_token_encoder"


    coloc_matching.rest.user_controller:
        class: ColocMatching\RestBundle\Controller\Rest\v1\User\UserController
        arguments:
            - "@logger"
            - "@jms_serializer"
            - "@coloc_matching.core.user_dto_manager"
            - "@coloc_matching.core.filter_factory"
            - "@coloc_matching.rest.response_factory"
            - "@event_dispatcher"
            - "@router"
            - "@coloc_matching.core.event_dispatcher_visitor"


    coloc_matching.rest.self_controller:
        class: ColocMatching\RestBundle\Controller\Rest\v1\User\SelfController
        arguments:
            - "@logger"
            - "@jms_serializer"
            - "@coloc_matching.core.user_dto_manager"
            - "@coloc_matching.core.historic_announcement_dto_manager"
            - "@coloc_matching.core.private_conversation_dto_manager"
            - "@coloc_matching.core.filter_factory"
            - "@coloc_matching.rest.response_factory"
            - "@coloc_matching.core.jwt_token_encoder"
            - "@coloc_matching.rest.visit_utils"


    coloc_matching.rest.profile_picture_controller:
        class: ColocMatching\RestBundle\Controller\Rest\v1\User\ProfilePictureController
        arguments:
            - "@logger"
            - "@jms_serializer"
            - "@coloc_matching.core.user_dto_manager"


    coloc_matching.rest.profile_controller:
        class: ColocMatching\RestBundle\Controller\Rest\v1\User\ProfileController
        arguments:
            - "@logger"
            - "@jms_serializer"
            - "@coloc_matching.core.user_dto_manager"


    coloc_matching.rest.preference_controller:
        class: ColocMatching\RestBundle\Controller\Rest\v1\User\PreferenceController
        arguments:
            - "@logger"
            - "@jms_serializer"
            - "@coloc_matching.core.user_dto_manager"


    coloc_matching.rest.announcement_controller:
        class: ColocMatching\RestBundle\Controller\Rest\v1\Announcement\AnnouncementController
        arguments:
            - "@logger"
            - "@jms_serializer"
            - "@coloc_matching.core.announcement_dto_manager"
            - "@coloc_matching.core.filter_factory"
            - "@coloc_matching.rest.response_factory"
            - "@event_dispatcher"
            - "@router"
            - "@coloc_matching.core.event_dispatcher_visitor"
            - "@coloc_matching.core.jwt_token_encoder"
            - "@security.authorization_checker"


    coloc_matching.rest.historic_announcement_controller:
        class: ColocMatching\RestBundle\Controller\Rest\v1\Announcement\HistoricAnnouncementController
        arguments:
            - "@logger"
            - "@jms_serializer"
            - "@coloc_matching.core.historic_announcement_dto_manager"
            - "@coloc_matching.core.filter_factory"
            - "@coloc_matching.rest.response_factory"


    coloc_matching.rest.announcement_picture_controller:
        class: ColocMatching\RestBundle\Controller\Rest\v1\Announcement\AnnouncementPictureController
        arguments:
            - "@logger"
            - "@jms_serializer"
            - "@coloc_matching.core.announcement_dto_manager"
            - "@security.authorization_checker"


    coloc_matching.rest.announcement_comment_controller:
        class: ColocMatching\RestBundle\Controller\Rest\v1\Announcement\AnnouncementCommentController
        arguments:
            - "@logger"
            - "@jms_serializer"
            - "@coloc_matching.core.announcement_dto_manager"
            - "@coloc_matching.core.filter_factory"
            - "@coloc_matching.rest.response_factory"
            - "@coloc_matching.core.jwt_token_encoder"
            - "@security.authorization_checker"


    coloc_matching.rest.housing_controller:
        class: ColocMatching\RestBundle\Controller\Rest\v1\Announcement\HousingController
        arguments:
            - "@logger"
            - "@jms_serializer"
            - "@coloc_matching.core.announcement_dto_manager"
            - "@security.authorization_checker"
