imports:
    - { resource: "admin_controllers.yml" }

services:
    coloc_matching.rest.authentication_controller:
        class: ColocMatching\RestBundle\Controller\Rest\v1\AuthenticationController
        arguments:
            - "@logger"
            - "@jms_serializer"
            - "@security.authorization_checker"
            - "@coloc_matching.core.user_dto_manager"
            - "@coloc_matching.core.jwt_token_encoder"
        public: true


    coloc_matching.rest.user_controller:
        class: ColocMatching\RestBundle\Controller\Rest\v1\User\UserController
        arguments:
            - "@logger"
            - "@jms_serializer"
            - "@security.authorization_checker"
            - "@coloc_matching.core.user_dto_manager"
            - "@coloc_matching.core.form_validator"
            - "@coloc_matching.core.event_dispatcher_visitor"
        public: true


    coloc_matching.rest.self_controller:
        class: ColocMatching\RestBundle\Controller\Rest\v1\User\SelfController
        arguments:
            - "@logger"
            - "@jms_serializer"
            - "@security.authorization_checker"
            - "@coloc_matching.core.user_dto_manager"
            - "@coloc_matching.core.historic_announcement_dto_manager"
            - "@coloc_matching.core.private_conversation_dto_manager"
            - "@coloc_matching.core.visit_dto_manager"
            - "@coloc_matching.core.form_validator"
            - "@coloc_matching.core.jwt_token_encoder"
        public: true


    coloc_matching.rest.profile_picture_controller:
        class: ColocMatching\RestBundle\Controller\Rest\v1\User\ProfilePictureController
        arguments:
            - "@logger"
            - "@jms_serializer"
            - "@security.authorization_checker"
            - "@coloc_matching.core.user_dto_manager"
        public: true


    coloc_matching.rest.profile_controller:
        class: ColocMatching\RestBundle\Controller\Rest\v1\User\ProfileController
        arguments:
            - "@logger"
            - "@jms_serializer"
            - "@security.authorization_checker"
            - "@coloc_matching.core.user_dto_manager"
        public: true


    coloc_matching.rest.preference_controller:
        class: ColocMatching\RestBundle\Controller\Rest\v1\User\PreferenceController
        arguments:
            - "@logger"
            - "@jms_serializer"
            - "@security.authorization_checker"
            - "@coloc_matching.core.user_dto_manager"
        public: true


    coloc_matching.rest.announcement_controller:
        class: ColocMatching\RestBundle\Controller\Rest\v1\Announcement\AnnouncementController
        arguments:
            - "@logger"
            - "@jms_serializer"
            - "@security.authorization_checker"
            - "@coloc_matching.core.announcement_dto_manager"
            - "@coloc_matching.core.form_validator"
            - "@event_dispatcher"
            - "@router"
            - "@coloc_matching.core.event_dispatcher_visitor"
            - "@coloc_matching.core.jwt_token_encoder"
        public: true


    coloc_matching.rest.announcement_picture_controller:
        class: ColocMatching\RestBundle\Controller\Rest\v1\Announcement\AnnouncementPictureController
        arguments:
            - "@logger"
            - "@jms_serializer"
            - "@security.authorization_checker"
            - "@coloc_matching.core.announcement_dto_manager"
            - "@security.authorization_checker"
        public: true


    coloc_matching.rest.announcement_comment_controller:
        class: ColocMatching\RestBundle\Controller\Rest\v1\Announcement\AnnouncementCommentController
        arguments:
            - "@logger"
            - "@jms_serializer"
            - "@security.authorization_checker"
            - "@coloc_matching.core.announcement_dto_manager"
            - "@coloc_matching.core.form_validator"
            - "@coloc_matching.core.jwt_token_encoder"
        public: true


    coloc_matching.rest.housing_controller:
        class: ColocMatching\RestBundle\Controller\Rest\v1\Announcement\HousingController
        arguments:
            - "@logger"
            - "@jms_serializer"
            - "@security.authorization_checker"
            - "@coloc_matching.core.announcement_dto_manager"
        public: true


    coloc_matching.rest.group_controller:
        class: ColocMatching\RestBundle\Controller\Rest\v1\Group\GroupController
        arguments:
            - "@logger"
            - "@jms_serializer"
            - "@security.authorization_checker"
            - "@coloc_matching.core.group_dto_manager"
            - "@coloc_matching.core.form_validator"
            - "@router"
            - "@coloc_matching.core.event_dispatcher_visitor"
            - "@coloc_matching.core.jwt_token_encoder"
        public: true


    coloc_matching.rest.group_picture_controller:
        class: ColocMatching\RestBundle\Controller\Rest\v1\Group\GroupPictureController
        arguments:
            - "@logger"
            - "@jms_serializer"
            - "@security.authorization_checker"
            - "@coloc_matching.core.group_dto_manager"
        public: true


    coloc_matching.rest.announcement_visit_controller:
        class: ColocMatching\RestBundle\Controller\Rest\v1\Visit\AnnouncementVisitController
        arguments:
            - "@logger"
            - "@jms_serializer"
            - "@security.authorization_checker"
            - "@coloc_matching.core.visit_dto_manager"
            - "@coloc_matching.core.announcement_dto_manager"
            - "@coloc_matching.core.form_validator"
        public: true


    coloc_matching.rest.user_visit_controller:
        class: ColocMatching\RestBundle\Controller\Rest\v1\Visit\UserVisitController
        arguments:
            - "@logger"
            - "@jms_serializer"
            - "@security.authorization_checker"
            - "@coloc_matching.core.visit_dto_manager"
            - "@coloc_matching.core.user_dto_manager"
            - "@coloc_matching.core.form_validator"
        public: true


    coloc_matching.rest.group_visit_controller:
        class: ColocMatching\RestBundle\Controller\Rest\v1\Visit\GroupVisitController
        arguments:
            - "@logger"
            - "@jms_serializer"
            - "@security.authorization_checker"
            - "@coloc_matching.core.visit_dto_manager"
            - "@coloc_matching.core.group_dto_manager"
            - "@coloc_matching.core.form_validator"
        public: true


    coloc_matching.rest.private_conversation_controller:
        class: ColocMatching\RestBundle\Controller\Rest\v1\Message\PrivateConversationController
        arguments:
            - "@logger"
            - "@jms_serializer"
            - "@security.authorization_checker"
            - "@coloc_matching.core.private_conversation_dto_manager"
            - "@coloc_matching.core.user_dto_manager"
            - "@coloc_matching.core.jwt_token_encoder"
        public: true


    coloc_matching.rest.invitation_controller:
        class: ColocMatching\RestBundle\Controller\Rest\v1\Invitation\InvitationController
        arguments:
            - "@logger"
            - "@jms_serializer"
            - "@security.authorization_checker"
            - "@coloc_matching.core.invitation_dto_manager"
        public: true


    coloc_matching.rest.announcement_invitation_controller:
        class: ColocMatching\RestBundle\Controller\Rest\v1\Invitation\AnnouncementInvitationController
        arguments:
            - "@logger"
            - "@jms_serializer"
            - "@security.authorization_checker"
            - "@coloc_matching.core.invitation_dto_manager"
            - "@coloc_matching.core.announcement_dto_manager"
            - "@coloc_matching.core.jwt_token_encoder"
        public: true


    coloc_matching.rest.group_invitation_controller:
        class: ColocMatching\RestBundle\Controller\Rest\v1\Invitation\GroupInvitationController
        arguments:
            - "@logger"
            - "@jms_serializer"
            - "@security.authorization_checker"
            - "@coloc_matching.core.invitation_dto_manager"
            - "@coloc_matching.core.group_dto_manager"
            - "@coloc_matching.core.jwt_token_encoder"
        public: true


    coloc_matching.rest.user_invitation_controller:
        class: ColocMatching\RestBundle\Controller\Rest\v1\Invitation\UserInvitationController
        arguments:
            - "@logger"
            - "@jms_serializer"
            - "@security.authorization_checker"
            - "@coloc_matching.core.invitation_dto_manager"
            - "@coloc_matching.core.user_dto_manager"
            - "@coloc_matching.core.group_dto_manager"
            - "@coloc_matching.core.announcement_dto_manager"
            - "@coloc_matching.core.jwt_token_encoder"
        public: true


    coloc_matching.rest.registration_controller:
        class: ColocMatching\RestBundle\Controller\Rest\v1\User\RegistrationController
        arguments:
            - "@logger"
            - "@jms_serializer"
            - "@security.authorization_checker"
            - "@coloc_matching.core.user_token_dto_manager"
            - "@coloc_matching.core.user_dto_manager"
            - "@router"
            - "@event_dispatcher"
        public: true


    coloc_matching.rest.request_password_controller:
        class: ColocMatching\RestBundle\Controller\Rest\v1\User\RequestPasswordController
        arguments:
            - "@logger"
            - "@jms_serializer"
            - "@security.authorization_checker"
            - "@coloc_matching.core.password_requester"
        public: true


    coloc_matching.rest.group_conversation_controller:
        class: ColocMatching\RestBundle\Controller\Rest\v1\Message\GroupConversationController
        arguments:
            - "@logger"
            - "@jms_serializer"
            - "@security.authorization_checker"
            - "@coloc_matching.core.group_conversation_dto_manager"
            - "@coloc_matching.core.group_dto_manager"
            - "@coloc_matching.core.jwt_token_encoder"
        public: true
